### ISSUE TITLE
Schreibfehler in Readme

### ISSUE THREAD

**Issue by L3P3** [LFF5644/site-spotifyApiService#1]
https://github.com/LFF5644/site-spotifyApiService/blob/eeb84909112d9358fca8f6746bd73284a2c7eaa6/README.md?plain=1#L6

- P.S.
- "Ich" am Satzanfang groß
- "scheiße" mit ß
- "Rechtschreibung" als Objekt groß

Red dir nicht ein, dass das schwer ist! Es ist einfach, bei JavaScript bekommst du solche Regeln auch hin!

**Comment by LFF5644** [comment]
haha lustig
