### ISSUE TITLE
Typenfehler

### ISSUE THREAD

**Issue by L3P3** [LFF5644/site-spotifyApiService#3]
Die Konfiguration ist ein `object`, aber `false` ist ein `boolean`. Diese Variable hat wegen dieser Zeile einen dynamischen Typen, V8 muss also extra prüfen und speichern, ob da gerade ein Objekt oder ein Boolean drin gespeichert ist. Du meinstest vermutlich das `null`-Objekt.

https://github.com/LFF5644/site-spotifyApiService/blob/eeb84909112d9358fca8f6746bd73284a2c7eaa6/spotify.service.js#L55

Die Variable darüber sollte dann auch mit `null` initialisiert werden, weil es sonst sogar noch schlimmer ist: Die Variable kann ein String, ein Objekt oder ein Boolean sein! AUA!

**Comment by LFF5644** [comment]
ja das kann gut sein ABER ich kann so um so einfacher im code schneller Prüfen https://github.com/LFF5644/site-spotifyApiService/blob/eeb84909112d9358fca8f6746bd73284a2c7eaa6/spotify.service.js#L57

**Comment by LFF5644** [comment]
ich finde das jz nicht als fehler sondern ok denn es machen viele leute so!

**Comment by L3P3** [comment]
Ne, in eine Variable entweder String, Objekt oder Boolean zu tun, machen nicht viele, sondern Trottel.
